-- M2 Catalog & Mapping seed: idempotent insertion of ~30 Alsterpavillon catalog items.
-- Generated by src/lib/crm/__seed__/catalog-seed.ts via renderCatalogSeedSql();
-- re-runnable: items + dispatch use ON CONFLICT, classifications guarded by status filter.

do $$
begin
  if to_regclass('public.catalog_items') is null then
    raise exception 'M2 seed precondition failed: public.catalog_items missing';
  end if;
  if to_regclass('public.catalog_dispatch') is null then
    raise exception 'M2 seed precondition failed: public.catalog_dispatch missing';
  end if;
  if to_regclass('public.catalog_classifications') is null then
    raise exception 'M2 seed precondition failed: public.catalog_classifications missing';
  end if;
end $$;

-- ────────────────────────────────────────────────────────────
-- Step 1: insert items idempotently (existing rows untouched)
-- ────────────────────────────────────────────────────────────

insert into public.catalog_items
  (sku, name, category, subcategory, default_price_net_cents, vat_rate, cost_default_net_cents, unit, is_active)
values
  ('AP-RM-ALSTER-D', 'Raummiete Alsterzimmer Ganztag', 'Raum', 'Vermietung', 120000, 19, 30000, 'flat', true),
  ('AP-RM-ALSTER-H', 'Raummiete Alsterzimmer Halbtag', 'Raum', 'Vermietung', 70000, 19, 20000, 'flat', true),
  ('AP-RM-PAVILLON-D', 'Raummiete Pavillon Ganztag', 'Raum', 'Vermietung', 180000, 19, 50000, 'flat', true),
  ('AP-RM-PAVILLON-H', 'Raummiete Pavillon Halbtag', 'Raum', 'Vermietung', 100000, 19, 30000, 'flat', true),
  ('AP-RM-TERRASSE-D', 'Raummiete Terrasse Ganztag (saisonal)', 'Raum', 'Vermietung', 80000, 19, 15000, 'flat', true),
  ('AP-TECH-BEAMER', 'Beamer Standard', 'Technik', 'AV', 15000, 19, 3000, 'flat', true),
  ('AP-TECH-LEINWAND', 'Leinwand 2x2m', 'Technik', 'AV', 8000, 19, 1000, 'flat', true),
  ('AP-TECH-MIC-HAND', 'Funkmikrofon Handheld', 'Technik', 'Audio', 5000, 19, 800, 'flat', true),
  ('AP-TECH-MIC-HEADSET', 'Funkmikrofon Headset', 'Technik', 'Audio', 6000, 19, 1000, 'flat', true),
  ('AP-TECH-PA-S', 'PA-Anlage klein', 'Technik', 'Audio', 12000, 19, 2500, 'flat', true),
  ('AP-TECH-BUEHNE-2', 'Bühnenelement 2x1m', 'Technik', 'Stage', 7500, 19, 1200, 'piece', true),
  ('AP-SVC-WAITER-H', 'Servicepersonal Stunde', 'Service', 'Personal', 4500, 19, 2800, 'hour', true),
  ('AP-SVC-BAR-H', 'Bar-Personal Stunde', 'Service', 'Personal', 4800, 19, 3000, 'hour', true),
  ('AP-OPS-EVENTLEAD', 'Eventleitung pauschal', 'Operations', 'Personal', 35000, 19, 18000, 'flat', true),
  ('AP-SVC-GARDEROBE', 'Garderobenservice mit Personal', 'Service', 'Personal', 25000, 19, 12000, 'flat', true),
  ('AP-OPS-AUFBAU', 'Aufbau / Abbau pauschal', 'Operations', 'Logistik', 30000, 19, 15000, 'flat', true),
  ('AP-CAT-KAFFEE-S', 'Kaffeepause klein', 'Catering', 'Pause', 850, 19, 350, 'person', true),
  ('AP-CAT-KAFFEE-L', 'Kaffeepause groß', 'Catering', 'Pause', 1500, 19, 600, 'person', true),
  ('AP-CAT-MITTAG-STD', 'Mittagsbuffet Standard', 'Catering', 'Buffet', 4500, 19, 1800, 'person', true),
  ('AP-CAT-DRINK-PKG', 'Tagungsgetränke-Paket', 'Catering', 'Getränke', 1800, 19, 700, 'person', true),
  ('AP-CAT-SEKT', 'Sektempfang', 'Catering', 'Empfang', 1200, 19, 500, 'person', true),
  ('AP-CAT-FINGERFOOD', 'Fingerfood-Auswahl', 'Catering', 'Buffet', 2200, 19, 900, 'person', true),
  ('AP-CAT-MENU-3G', 'Abendmenü 3-Gänge', 'Catering', 'Menu', 5800, 19, 2300, 'person', true),
  ('AP-CAT-KUCHEN', 'Kuchenbuffet', 'Catering', 'Pause', 1400, 19, 550, 'person', true),
  ('AP-CAT-SNACKBOX', 'Snackbox to-go', 'Catering', 'Take-Away', 1100, 7, 450, 'person', true),
  ('AP-OPS-REINIGUNG', 'Endreinigung Pauschal', 'Reinigung', NULL, 18000, 19, 8000, 'flat', true),
  ('AP-OPS-CHAIR-BANK', 'Bestuhlung Bankett (pro Stuhl)', 'Setup', 'Möbel', 250, 19, 50, 'piece', true),
  ('AP-OPS-CHAIR-REIHE', 'Bestuhlung Reihe (pro Stuhl)', 'Setup', 'Möbel', 200, 19, 50, 'piece', true),
  ('AP-OPS-STEHTISCH', 'Stehtisch', 'Setup', 'Möbel', 1200, 19, 200, 'piece', true),
  ('AP-OPS-MUELL', 'Müllentsorgung pauschal', 'Reinigung', NULL, 4500, 19, 1500, 'flat', true),
  ('AP-PRINT-MAPPE', 'Tagungsmappe gedruckt', 'Drucksachen', 'Materialien', 350, 7, 120, 'piece', true)
on conflict (sku) do nothing;

-- ────────────────────────────────────────────────────────────
-- Step 2: upsert dispatch mappings (rebases is_primary on every run)
-- ────────────────────────────────────────────────────────────

insert into public.catalog_dispatch (catalog_item_id, dispatch_role, is_primary)
select ci.id, d.dispatch_role, d.is_primary
from (values
  ('AP-RM-ALSTER-D', 'operations', true),
  ('AP-RM-ALSTER-H', 'operations', true),
  ('AP-RM-PAVILLON-D', 'operations', true),
  ('AP-RM-PAVILLON-H', 'operations', true),
  ('AP-RM-TERRASSE-D', 'operations', true),
  ('AP-TECH-BEAMER', 'tech', true),
  ('AP-TECH-LEINWAND', 'tech', true),
  ('AP-TECH-MIC-HAND', 'tech', true),
  ('AP-TECH-MIC-HEADSET', 'tech', true),
  ('AP-TECH-PA-S', 'tech', true),
  ('AP-TECH-BUEHNE-2', 'tech', true),
  ('AP-TECH-BUEHNE-2', 'operations', false),
  ('AP-SVC-WAITER-H', 'service', true),
  ('AP-SVC-BAR-H', 'service', true),
  ('AP-OPS-EVENTLEAD', 'operations', true),
  ('AP-SVC-GARDEROBE', 'service', true),
  ('AP-OPS-AUFBAU', 'operations', true),
  ('AP-OPS-AUFBAU', 'service', false),
  ('AP-CAT-KAFFEE-S', 'kitchen', true),
  ('AP-CAT-KAFFEE-S', 'service', false),
  ('AP-CAT-KAFFEE-L', 'kitchen', true),
  ('AP-CAT-KAFFEE-L', 'service', false),
  ('AP-CAT-MITTAG-STD', 'kitchen', true),
  ('AP-CAT-MITTAG-STD', 'service', false),
  ('AP-CAT-DRINK-PKG', 'kitchen', true),
  ('AP-CAT-DRINK-PKG', 'service', false),
  ('AP-CAT-SEKT', 'service', true),
  ('AP-CAT-SEKT', 'kitchen', false),
  ('AP-CAT-FINGERFOOD', 'kitchen', true),
  ('AP-CAT-FINGERFOOD', 'service', false),
  ('AP-CAT-MENU-3G', 'kitchen', true),
  ('AP-CAT-MENU-3G', 'service', false),
  ('AP-CAT-KUCHEN', 'kitchen', true),
  ('AP-CAT-KUCHEN', 'service', false),
  ('AP-CAT-SNACKBOX', 'kitchen', true),
  ('AP-CAT-SNACKBOX', 'purchase', false),
  ('AP-OPS-REINIGUNG', 'operations', true),
  ('AP-OPS-CHAIR-BANK', 'operations', true),
  ('AP-OPS-CHAIR-BANK', 'service', false),
  ('AP-OPS-CHAIR-REIHE', 'operations', true),
  ('AP-OPS-CHAIR-REIHE', 'service', false),
  ('AP-OPS-STEHTISCH', 'operations', true),
  ('AP-OPS-MUELL', 'operations', true),
  ('AP-OPS-MUELL', 'purchase', false),
  ('AP-PRINT-MAPPE', 'purchase', true),
  ('AP-PRINT-MAPPE', 'operations', false)
) as d(sku, dispatch_role, is_primary)
join public.catalog_items ci on ci.sku = d.sku
on conflict (catalog_item_id, dispatch_role) do update
  set is_primary = excluded.is_primary;

-- ────────────────────────────────────────────────────────────
-- Step 3: flip classifications to 'classified' for all seed items
-- (only when not already classified — preserves classified_at on re-run)
-- ────────────────────────────────────────────────────────────

update public.catalog_classifications cc
set classification_status = 'classified',
    classified_at = now()
where cc.classification_status <> 'classified'
  and cc.catalog_item_id in (
    select id from public.catalog_items where sku in (
      'AP-RM-ALSTER-D',
      'AP-RM-ALSTER-H',
      'AP-RM-PAVILLON-D',
      'AP-RM-PAVILLON-H',
      'AP-RM-TERRASSE-D',
      'AP-TECH-BEAMER',
      'AP-TECH-LEINWAND',
      'AP-TECH-MIC-HAND',
      'AP-TECH-MIC-HEADSET',
      'AP-TECH-PA-S',
      'AP-TECH-BUEHNE-2',
      'AP-SVC-WAITER-H',
      'AP-SVC-BAR-H',
      'AP-OPS-EVENTLEAD',
      'AP-SVC-GARDEROBE',
      'AP-OPS-AUFBAU',
      'AP-CAT-KAFFEE-S',
      'AP-CAT-KAFFEE-L',
      'AP-CAT-MITTAG-STD',
      'AP-CAT-DRINK-PKG',
      'AP-CAT-SEKT',
      'AP-CAT-FINGERFOOD',
      'AP-CAT-MENU-3G',
      'AP-CAT-KUCHEN',
      'AP-CAT-SNACKBOX',
      'AP-OPS-REINIGUNG',
      'AP-OPS-CHAIR-BANK',
      'AP-OPS-CHAIR-REIHE',
      'AP-OPS-STEHTISCH',
      'AP-OPS-MUELL',
      'AP-PRINT-MAPPE'
    )
  );
